### ISSUE TITLE
Array type

### ISSUE THREAD

**Issue by mm-saad** [silicann/raml2html-werk-theme#3]
Hi,
I have created a Type (in the list of types) called "allImportOrderedFields" in the response i have an array of this type, so to document this in Raml, i set in the responses :

responses:
--200:
----body:
------application/json:
--------type: allImportOrderedFields[]

so the type is an array of allImportOrderedFields.
In the raml2html-werk-theme in the response area the type is not present, i checked on 3 other templates (with the same code) and i can see the type for this resource.
I join 2 pictures to this issue : one with another theme and on with the theme raml2html-werk-theme.
I hope that you can edit this.

Thanks

####################################################
another theme : 
<img width="890" alt="capture d ecran 2018-07-09 a 12 19 58" src="https://user-images.githubusercontent.com/18479708/42445135-6f6610c6-8372-11e8-8095-793c4049abac.png">

####################################################
raml2html-werk-theme :
<img width="434" alt="capture d ecran 2018-07-09 a 12 17 19" src="https://user-images.githubusercontent.com/18479708/42445059-32bb77f6-8372-11e8-94a2-0da61a4c1510.png">

**Comment by kmohrf** [comment]
could you please provide a stripped copy of the raml file with just the part that is not working?

**Comment by mm-saad** [comment]
![capture d ecran 2018-07-09 a 15 10 24](https://user-images.githubusercontent.com/18479708/42452430-3fb28676-838a-11e8-87f1-ee371fb43902.png)
